export const BOOK_APPOINTMENT_LOADING = "BOOK_APPOINTMENT_LOADING";
export const BOOK_APPOINTMENT_SUCCESS = "BOOK_APPOINTMENT_SUCCESS";
export const BOOK_APPOINTMENT_ERROR = "BOOK_APPOINTMENT_ERROR";
export const BOOK_APPOINTMENT_RESET = "BOOK_APPOINTMENT_RESET";
